config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/about'

  devise_for :users
  resources :users

  resources :official_articles do
    resources :article_comments
    member do
      post :like
      post :unlike
    end
    collection do
      get :search
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  resource :setting do
    member do
      get :password
    end
  end
  
  resources :posts do
    collection do
      get :search
    end
  end  


  get 'topics/node:id', to: 'topics#node', as: 'node_topics'

  resources :topics do
    member do
      post :answer
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      get :ban
      post :action
      
      post :like
      post :unlike
    end
    collection do
      get :search
      get :no_answer
      get :popular

      get :favorites
      # post :preview
    end
    resources :answers do
      member do
        get :answer_to
      end
    end
  end
  resources :post_comments
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      resources :post_comments
      member do
        post :favorite
        post :unfavorite
      end
    end
    collection do
      get :search
    end
  end
  resources :meetup_groups do
    resources :meetup_comments
    collection do
      get :search
      get :about
    end
    
    member do
      post :favorite
      post :unfavorite
    end
        
  end
  resources :jobs do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :site_nodes

  resources :sites do
    collection do
      get :search
    end
  end
  resources :courses do
    resources :course_comments
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :projects do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end

  namespace :account do
    resources :users
    resources :courses
    resources :groups
    resources :posts
    resources :topics
    resources :jobs
    resources :meetup_groups
    resources :passwords
  end

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :groups do
      collection do
        post :bulk_update
      end
      resources :posts
    end
    resources :versions do
      post :undo
    end
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
      collection do
        post :bulk_update
      end
    end
    resources :nodes
    resources :sections
    resources :meetup_groups do
      collection do
        post :bulk_update
      end
    end
    resources :projects do
      collection do
        post :bulk_update
      end
      resource :project_grade, :controller => "project_grades"
    end
    resources :article_categories do
      collection do
        post :bulk_update
      end
    end
    resources :official_articles do
      collection do
        post :bulk_update
      end
    end
    resources :jobs do
      collection do
        post :bulk_update
      end
      member do
        post :publish
        post :hide
      end
    end
    resources :site_nodes do
      collection do
        post :bulk_update
      end
    end
    resources :sites do
      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, :controller => "user_profiles"
      collection do
        post :bulk_update
      end
    end
    resources :courses do
      collection do
        post :bulk_update
      end
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_paper_trail
  validates :title, presence: true
  validates :description, presence: true
  validates :logo, presence: true

  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user

  mount_uploader :logo,GroupLogoUploader

  STATUS = ["draft", "public", "private"]
  validates_inclusion_of :status, :in => STATUS
  # Scope #
  scope :random5, -> { limit(5).order("RANDOM()") }
  scope :published, -> { where(:status => "public")}
  scope :recent, -> { order("created_at DESC")}
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.recent.paginate(:page => params[:page], :per_page => 10)
    @participated_groups = current_user.participated_groups.recent.paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]
  before_action :validate_search_key, only: [:search]

  def index
    @groups = Group.all.recent.paginate(:page => params[:page], :per_page => 20)
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      current_user.join!(@group)
      redirect_to admin_groups_path
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to admin_groups_path, notice:"更新成功！"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, alert: "删除成功！"
  end

  def search
    if @query_string.present?
      search_result = Group.ransack(@search_criteria).result(:distinct => true)
      @groups = search_result.paginate(:page => params[:page], :per_page => 20 )
    end
  end

  def bulk_update
    total = 0
    Array(params[:ids]).each do |group_id|
      group = Group.find(group_id)
      group.destroy
      total += 1
    end

    flash[:alert] = "成功完成 #{total} 笔"
    redirect_to admin_jobs_path
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end


  def search_criteria(query_string)
    { :title_cont => query_string }
  end

  private

  def find_group_and_check_permission
    @group = Group.find(params[:id])

    unless current_user.is_editor?
      redirect_to root_path, alert: "抱歉，您没有相应的权限！"
    end
  end

  def group_params
    params.require(:group).permit(:title, :logo, :remove_logo, :description, :status)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :join, :quit]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]
  before_action :validate_search_key, only: [:search]

  def index
    @groups = Group.published.recent.paginate(:page => params[:page], :per_page => 12)

    @posts = case params[:order]
             when 'by_hot'
               #按评论数量排序,后期改为只比较最近一周的
               Post.all.paginate(:page => params[:page], :per_page => 10).sort_by{|post| -post.post_comments.count}
             else
               Post.all.recent.paginate(:page => params[:page], :per_page => 10)
             end
  end

  def show
    @group = Group.find(params[:id])
    set_page_title @group.title
    set_page_description "#{@group.description}"
    # 随机推荐5个相同类型的话题（去除当前话题），后期修改为真正的相关话题
    @commends = Group.published.where.not(:id => @group.id ).random5
    @posts = case params[:order]
             when 'by_hot'
               #按评论数量排序
               @group.posts.paginate(:page => params[:page], :per_page => 10).sort_by{|post| -post.post_comments.count}

             else
               @group.posts.recent.paginate(:page => params[:page], :per_page => 10)
             end
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      current_user.join!(@group)
      redirect_to groups_path
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice:"更新成功！"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, alert: "删除成功！"
  end

  def join
   @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "成功加入该小组！"
    else
      flash[:warning] = "你已经是本讨论版成员了！"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "已退出本讨论版！"
    else
      flash[:warning] = "你不是本讨论版成员，怎么退出 XD"
    end

    redirect_to group_path(@group)
  end

  def search
    if @query_string.present?
      search_result = Group.ransack(@search_criteria).result(:distinct => true)
      @groups = search_result.paginate(:page => params[:page], :per_page => 20 )
    end
  end


  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end


  def search_criteria(query_string)
    { :title_cont => query_string }
  end

  private

  def find_group_and_check_permission
    @group = Group.find(params[:id])

    if current_user != @group.user
      redirect_to root_path, alert: "抱歉，您没有相应的权限！"
    end
  end

  def group_params
    params.require(:group).permit(:title, :logo, :remove_logo, :description, :status)
  end

end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_description(group)
    simple_format(group.description)
  end
    
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/groups/_group_form.html.erb
<%= simple_form_for @group do |f| %>

  <div class="form-group">
    <%= f.label "小组logo" %>
    <%= f.file_field :logo, :class => "form-control" %>
    <% if f.object.logo.present? %>
      <label>
        <%= f.check_box :remove_logo %> 删除logo
      </label>
      <%= link_to f.object.logo.filename, f.object.logo.url, :target => "_blank" %>
    <% end %>
  </div>
  
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"}, :label => "小组名称" %>
    <%= f.input :description, as: :wysihtml5, :label => "小组介绍", input_html: { rows: "20"} %>
  </div>
  <%= f.submit "提交审核", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/groups/_group_item.html.erb
<div class="col-md-3 group-item"> 
  <div class="group-card">
    <% if group.logo.present? %>
      <%= link_to image_tag(group.logo.url(:group_index_logo)),group_path(group), :target => "_blank" %>
    <% else %>
      <img src="https://ww2.sinaimg.cn/large/006tKfTcly1fnt7p9w5h6j306o06owec.jpg" alt="group_logo">
    <% end %>

    <div class="group-card-title text-center">
      <p ><%= link_to(truncate(group.title,:length => 16) ,group_path(group)) %></p>
      <span>
        <i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= group.members.count %>
      </span>
    </div>
    
  </div>
  <br>
</div>

app/views/groups/_search_bar.html.erb
<div class="container search-input">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2" ">
    <%= form_tag search_groups_path, :method => :get, :class => "jobs-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="搜索小组关键字...">

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/_sidebar_for_group_index.html.erb
<% if current_user %>
  <div class="panel panel-default">
    <div class="panel-body">
      <!-- 头像 -->
      <div class="text-center">
        <div class="avatar-80">
          <div class="avatar-group-index">
            <img src= "<%= render_user_avatar(@current_user, 80) %>">
          </div>
        </div>
      </div>
      <!-- 用户名 -->
      <div class="article-username text-center">
        <%= @current_user.display_name %>
      </div>
      
      <!-- 简介 -->
      <div class="article-author-summary">
        <%= simple_format(@current_user.summary) %>
        
      </div>
      <hr>
      
      <!-- 我创建的小组 -->
          
    </div>
  </div>
<% end %>


<!-- <div class="panel panel-default">
  <div class="panel-heading">小组分类</div>
  <div class="panel-body">
    该功能尚未完成，重构为2级分类
  </div>
</div> -->

<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to t('申请创建小组'), new_group_path, class: 'btn btn-danger btn-block' %>  
  </div>
</div>

<%= render "common/sidebar_box_tips" %>

<div class="panel panel-default">
  <div class="panel-heading">统计信息</div>
  <ul class="list-group">
    <li class="list-group-item">社区会员: <%= User.count %> 人</li>
    <li class="list-group-item">小组数: <%= Group.count %> 个</li>
    <li class="list-group-item">帖子数: <%= Post.count %> 条</li>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">广告位</div>
  <div class="panel-body ads-image-css">
    <img src= "https://ww4.sinaimg.cn/large/006tKfTcly1fnt6b3yncgj30ik0t8dhw.jpg" >
  </div>
</div>

app/views/groups/_sidebar_for_group_show.html.erb
<% if current_user %>
  <div class="panel panel-default">
    <div class="panel-body">
      <!-- 头像 -->
      <div class="text-center">
        <div class="avatar-80">
          <div class="avatar-group-index">
            <img src= "<%= render_user_avatar(@current_user, 80) %>">
          </div>
        </div>
      </div>
      <!-- 用户名 -->
      <div class="article-username text-center">
        <%= @current_user.display_name %>
      </div>
      
      <!-- 简介 -->
      <div class="article-author-summary">
        <%= simple_format(@current_user.summary) %>
        
      </div>
      <hr>
      
      <!-- 我创建的小组 -->
      <%= link_to t('我的小组主页'), account_groups_path, class: 'btn btn-default btn-block' %>
          
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to t('我要发言'), new_group_post_path(@group), class: 'btn btn-default btn-block' %>  
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
    <br>
    
    <div class="post-share text-center">
      <%= social_share_button_tag(@group.title) %><!-- 社交分享 -->
    </div>
  
    <hr />
    <div class="reply-buttons">
      <div class="total text-center">
        共计 <b>7</b> 条帖子
      </div>
    </div>
    
    <% if current_user && current_user == @group.user %>
      <hr/>
      <div class="post-admin text-center">
        <label class="label label-success"> <%= link_to("编辑小组信息", edit_group_path(@group))%></label> 
        <label class="label label-danger"><%= link_to("删除小组", group_path(@group), 
                        method: :delete, data: { confirm: "Are you sure?" } )%></label> 
      </div>                  
    <% end %>
      
    <br>
    <a href="#" class="btn btn-block btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to t('申请创建小组'), new_group_path, class: 'btn btn-danger btn-block' %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">这个小组的成员也喜欢</div>
  <div class="panel-body">
    <% @commends.each do |group| %>
      <p>
        <%= link_to group.title, group_path(group) %> · <span class="badge"><%= group.posts.size %></span>
      </p>
    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">小组信息</div>
  <ul class="list-group">
    <li class="list-group-item">小组名称：<%= link_to(@group.title, group_path(@group)) %></li>
    <li class="list-group-item">小组成员: <%= Group.count %> 人</li>
    <li class="list-group-item">帖子数: <%= @group.posts.count %> 条</li>
    <li class="list-group-item">
      <span class="">
        <% if current_user && current_user.is_member_of?(@group) %>
          <label class="label label-success"> 我是小组成员 </label>
          
          <% if (current_user && current_user != @group.user) && current_user.is_member_of?(@group) %>
            &nbsp;&nbsp;<label class="label label-warning"><%= link_to("退出小组", quit_group_path(@group), method: :post) %></label>
          <% end %>
          
        <% else %>
          <label class="label label-warning"> 不是小组成员 </label>
          &nbsp;&nbsp;<label class="label label-success"><%= link_to("加入小组", join_group_path(@group), method: :post) %></label>
        <% end %>
      </span>
    </li>  
  </ul>
</div>

<div class="panel panel-default ads">
  <div class="panel-body ads-image-css">
    <img src= "https://ww4.sinaimg.cn/large/006tKfTcly1fnt6b3yncgj30ik0t8dhw.jpg" >
  </div>
</div>

app/views/groups/edit.html.erb
<div class="container">
  <%= render "common/flashes" %>
</div>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">更新小组信息</div>
    <div class="panel-body">
      <%= render "group_form" %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="row search-for-topic search-secticon">
  <%= render "groups/search_bar" %>
</div>

<div class="container">
  <%= render "common/flashes" %>
</div>

<div class="container">
  <div class="col-md-9 group-index-box">

    <div class="row">
      <%= render :partial => "group_item", :collection => @groups, :as => :group %>
      <div class="text-center">
        <%= will_paginate @groups, renderer: BootstrapPagination::Rails, :previous_label => t('上一页'), :next_label => t('下一页') %>
      </div>
    </div>

    <br>

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to("最新动态", groups_path) %> |
        <%= link_to("热门帖子", groups_path(:order => "by_hot")) %>
      </div>
      <div class="panel-body">
        <% @posts.each do |post| %>
          <p>
            <%= link_to post.group.title, group_path(post.group) %> · <%= link_to truncate(post.title,:length => 23), group_post_path(post.group,post) %>  <span class="badge"><%= post.post_comments.count %></span>
            <span class="pull-right">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= post.user.display_name %> ·
              <span class="glyphicon glyphicon-time" aria-hidden="true"></span> <%= time_tag(post.created_at) %>
            </span>
          </p>
        <% end %>
        
        <div class="text-center">
          <%= will_paginate @posts, renderer: BootstrapPagination::Rails, :previous_label => t('上一页'), :next_label => t('下一页') %>
        </div>
      </div><!-- /panel-body -->

    </div>
  </div>

  <div class="sidebar col-md-3">
    <%= render "sidebar_for_group_index" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <%= render "common/flashes" %>
</div>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">新增小组信息</div>
    <div class="panel-body">
      <%= render "group_form" %>
    </div>
  </div>
</div>

app/views/groups/search.html.erb
<div class="row search-for-topic search-secticon">
  <%= render "groups/search_bar" %>
</div>

<div class="container">
  <%= render "common/flashes" %>
</div>

<div class="container">
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-body">
        <% if @query_string.blank? %>
            <h4 class="search-info-title">搜索信息不能为空，请输入关键字搜索</h4>
        <% elsif @groups.blank? %>
            <br>
            <h4 class="search-info-title">亲，没有搜索到相关小组信息哦，要不换个关键词试试？</h4>
        <% else %>
            <h4 class="search-info-title"> 有关"<%= @query_string %>"的小组 </h4>
            <hr>
            <% @groups.each do |group| %>
              <div class="row"> 
                <div class="col-md-3">
                  <% if group.logo.present? %>
                    <%= link_to image_tag(group.logo.url(:group_index_logo)),group_path(group) %>
                  <% end %>
                </div>
                <div class="col-md-9">
                  <h4><%= link_to render_highlight_content(group,@query_string),group_path(group) %></h4>
                  <div class="row">
                    组长：<%= group.user.display_name %>，成员数：<%= group.members.count %>
                    主题：<%= group.posts.count %>
                  </div>  
                </div>
              </div> 
              <hr/>
            <% end %>
        <% end %>
        <% if @groups.present? %>
          <div class="text-center">
            <%= will_paginate @groups, renderer: BootstrapPagination::Rails, :previous_label => t('上一页'), :next_label => t('下一页') %>
          </div>
        <% end %>
      </div><!-- /panel-body -->
      
    </div>
  </div>

  <div class="sidebar col-md-3">
    <%= render "sidebar_for_group_index" %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <%= render "common/flashes" %>
</div>

<div class="container">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-1">
            <% if @group.logo.present? %>
              <%= link_to image_tag(@group.logo.url(:thumb)),group_path(@group) %>
            <% end %>
          </div>
          <div class="col-md-11">
            <h1 class="panel-title">&nbsp;&nbsp;&nbsp;<%= @group.title %></h1>
          </div>
        </div>
      </div>
      <div class="panel-body">


        <div class="col-md-12">
          创建于<%= time_tag(@group.created_at) %>
          组长：<%= @group.user.display_name %>
          <p><%= render_group_description(@group) %></p>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to("最新话题 ", group_path(@group) ) %> /
        <%= link_to("热门话题", group_path(@group, :order => "by_hot")) %>
        <!-- /<span>推荐话题</span>/<span>精华帖</span> -->
      </div>
      <div class="panel-body">

        <% @posts.each do |post| %>
          <p>
            <%= link_to post.group.title, group_path(post.group) %> · <%= link_to truncate(post.title,:length => 23), group_post_path(post.group,post) %>  <span class="badge"><%= post.post_comments.count %></span>
            <span class="pull-right">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= post.user.display_name %> ·
              <span class="glyphicon glyphicon-time" aria-hidden="true"></span> <%= time_tag(post.created_at) %>
            </span>
          </p>
        <% end %>
        <div class="text-center">
          <%= will_paginate @posts, renderer: BootstrapPagination::Rails, :previous_label => t('上一页'), :next_label => t('下一页') %>
        </div>
      </div>
    </div>
  </div>

  <div class="sidebar col-md-3">
    <%= render "sidebar_for_group_show" %>
  </div>
</div>