config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/about'

  devise_for :users
  resources :users

  resources :official_articles do
    resources :article_comments
    member do
      post :like
      post :unlike
    end
    collection do
      get :search
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  resource :setting do
    member do
      get :password
    end
  end
  
  resources :posts do
    collection do
      get :search
    end
  end  


  get 'topics/node:id', to: 'topics#node', as: 'node_topics'

  resources :topics do
    member do
      post :answer
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      get :ban
      post :action
      
      post :like
      post :unlike
    end
    collection do
      get :search
      get :no_answer
      get :popular

      get :favorites
      # post :preview
    end
    resources :answers do
      member do
        get :answer_to
      end
    end
  end
  resources :post_comments
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      resources :post_comments
      member do
        post :favorite
        post :unfavorite
      end
    end
    collection do
      get :search
    end
  end
  resources :meetup_groups do
    resources :meetup_comments
    collection do
      get :search
      get :about
    end
    
    member do
      post :favorite
      post :unfavorite
    end
        
  end
  resources :jobs do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :site_nodes

  resources :sites do
    collection do
      get :search
    end
  end
  resources :courses do
    resources :course_comments
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :projects do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end

  namespace :account do
    resources :users
    resources :courses
    resources :groups
    resources :posts
    resources :topics
    resources :jobs
    resources :meetup_groups
    resources :passwords
  end

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :groups do
      collection do
        post :bulk_update
      end
      resources :posts
    end
    resources :versions do
      post :undo
    end
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
      collection do
        post :bulk_update
      end
    end
    resources :nodes
    resources :sections
    resources :meetup_groups do
      collection do
        post :bulk_update
      end
    end
    resources :projects do
      collection do
        post :bulk_update
      end
      resource :project_grade, :controller => "project_grades"
    end
    resources :article_categories do
      collection do
        post :bulk_update
      end
    end
    resources :official_articles do
      collection do
        post :bulk_update
      end
    end
    resources :jobs do
      collection do
        post :bulk_update
      end
      member do
        post :publish
        post :hide
      end
    end
    resources :site_nodes do
      collection do
        post :bulk_update
      end
    end
    resources :sites do
      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, :controller => "user_profiles"
      collection do
        post :bulk_update
      end
    end
    resources :courses do
      collection do
        post :bulk_update
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @official_articles = OfficialArticle.published.recent.paginate(:page => params[:page], :per_page => 7)
    @article_hots = OfficialArticle.published.paginate(:page => params[:page], :per_page => 7).sort_by{|official_article| -official_article.article_comments.count}
    @topics = Topic.published.paginate(:page => params[:page], :per_page => 8)
    @groups = Group.published.recent.paginate(:page => params[:page], :per_page => 6)
    @projects = Project.published.recent.paginate(:page => params[:page], :per_page => 6)
    @courses = Course.published.recent.paginate(:page => params[:page], :per_page => 6) 

    @online_meetups = MeetupGroup.published.recent.online_meetup.paginate(:page => params[:page], :per_page => 3)
    @offline_meetups = MeetupGroup.published.recent.offline_meetup.paginate(:page => params[:page], :per_page => 3)
    @internship_jobs = Job.published.recent.internship_job.paginate(:page => params[:page], :per_page => 3)
    @fulltime_jobs = Job.published.recent.fulltime_job.paginate(:page => params[:page], :per_page => 3)

  end

  def about
    # render layout: false
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_articles_for_index.html.erb
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-header">
      <div class="row">
        <span><a href="/official_articles"><img src="/images/home_tool2.png"></a> </span><span>  最新资讯 </span><a class="pull-right" href="/official_articles">更多</a>
      </div>
    </div>

    <div class="panel-body">
      <% @official_articles.each do |official_article| %>
        <div class="official_article-item">
          <h4><%= link_to(truncate(official_article.title,:length => 34), official_article_path(official_article)) %></h4>
        </div>
      <% end %>
      <hr>
      <p class="text-center"><%= link_to("更多最新资讯", official_articles_path) %></p>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-header">
      <div class="row">
        <span><a href="/topics"><img src="/images/home_tool2.png"></a> </span><span>  热门资讯 </span><a class="pull-right" href="/topics">更多</a>
      </div>
    </div>

    <div class="panel-body">
      <% @article_hots.each do |article_hot| %>
        <div class="official_article-item">
          <h4><%= link_to(truncate(article_hot.title,:length => 34), official_article_path(article_hot)) %></h4>
        </div>
      <% end %>
      <hr>
      <p class="text-center"><%= link_to("更多热门资讯", official_articles_path) %></p>
    </div>
  </div>
</div>

app/views/welcome/_courses_for_index.html.erb
<div class="panel panel-default">
  <div class="panel-header">
    <div class="row">
      <span><a href="/groups"><img src="/images/home_tool3.png"></a> </span><span>  课程 </span>
    </div>
  </div>

  <div class="panel-body">
    <% @courses.each do |course| %>
      <div class="col-md-2 course-item">
        <div class="course-card">
          <% if course.logo.present? %>
            <%= link_to image_tag(course.logo.url(:medium)),course_path(course), :target => "_blank" %>
          <% else %>
            <img src="https://ww2.sinaimg.cn/large/006tKfTcly1fnt7p9w5h6j306o06owec.jpg" alt="course_logo">
          <% end %>

          <div class="course-card-title text-center">
            <p><%= link_to(truncate(course.title,:length => 16),course_path(course)) %></p>
          </div>

        </div>
      </div>
    <% end %>
    
  </div>
  
  <hr>
  <p class="text-center"><%= link_to("更多课程", courses_path) %></p>
</div>

app/views/welcome/_groups_for_index.html.erb
<div class="panel panel-default">
  <div class="panel-header">
    <div class="row">
      <span><a href="/groups"><img src="/images/home_tool7.png"></a> </span><span>  小组 </span>
    </div>
  </div>

  <div class="panel-body">
    <% @groups.each do |group| %>
      <div class="col-xl-3 col-lg-2 col-md-2 col-sm-4 col-xs-4 group-item">
        <div class="group-card">
          <% if group.logo.present? %>
            <%= link_to image_tag(group.logo.url(:group_index_logo)),group_path(group), :target => "_blank" %>
          <% else %>
            <img src="https://ww2.sinaimg.cn/large/006tKfTcly1fnt7p9w5h6j306o06owec.jpg" alt="group_logo">
          <% end %>

          <div class="group-card-title text-center">
            <p ><%= link_to(truncate(group.title,:length => 16),group_path(group)) %></p>
            <span>
              <i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= group.members.count %>
            </span>
          </div>

        </div>
      </div>
    <% end %>
  </div>
  <hr>
  <p class="text-center"><%= link_to("更多小组", groups_path) %></p>
</div>

app/views/welcome/_home_tool.html.erb
<div class="container">
  <div class="row home-tool-box">
    <a class="tool-item" href="/topics"><img src="/images/home_tool5.png"><p class="title ellipsis">社区</p></a>
    <a class="tool-item" href="/official_articles"><img src="/images/home_tool2.png"><p class="title ellipsis">资讯</p></a>
    <a class="tool-item" href="/projects"><img src="/images/home_tool1.png"><p class="title ellipsis">评级</p></a>
    <a class="tool-item" href="/groups"><img src="/images/home_tool7.png"><p class="title ellipsis">小组</p></a>
    <a class="tool-item" href="/courses"><img src="/images/home_tool3.png"><p class="title ellipsis">课程</p></a>
    <a class="tool-item" href="/meetup_groups"><img src="/images/home_tool9.png"><p class="title ellipsis">活动</p></a>
    <a class="tool-item" href="/jobs"><img src="/images/home_tool4.png"><p class="title ellipsis">机会</p></a>
    <a class="tool-item" href="/sites"><img src="/images/home_tool6.png"><p class="title ellipsis">导航</p></a>
    <a class="tool-item" href="/welcome/about"><img src="/images/home_tool8.png"><p class="title ellipsis">关于</p></a>
  </div>
</div>

app/views/welcome/_jobs_for_index.html.erb
<div class="panel panel-default">
  <div class="panel-header">
    <div class="row">
      <span><a href="/groups"><img src="/images/home_tool4.png"></a> </span><span>机会</span>
    </div>
  </div>

  <div class="panel-body">
    <div class="row home-job">
      <div class="col-md-6">
        <% @internship_jobs.each do |job| %>
          <div class="job-item">
            <p><span><%= job.publisher %></span><span class="pull-right">更新于 <%= time_tag(job.updated_at) %></span></p>
            <h4><%= link_to(job.title, job_path(job)) %></h4>
            <p><i class="fa fa-street-view" aria-hidden="true"></i> <%= job.city %></p>
            <p><i class="fa fa-clock-o" aria-hidden="true"></i> <%= job.deadline %></p>
            <p><span class="label label-success"><%= t(job.category, :scope => "job.category") %></span></p>
            <hr>
          </div>
        <% end %>
        <p class="text-center"><%= link_to("更多实习机会", jobs_path(:order => "by_internship")) %></p>
      </div>

      <div class="col-md-6">
        <% @fulltime_jobs.each do |job| %>
          <div class="job-item">
            <p><span><%= job.publisher %></span><span class="pull-right">更新于 <%= time_tag(job.updated_at) %></span></p>
            <h4><%= link_to(job.title, job_path(job)) %></h4>
            <p><i class="fa fa-street-view" aria-hidden="true"></i> <%= job.city %></p>
            <p><i class="fa fa-clock-o" aria-hidden="true"></i> <%= job.deadline %></p>
            <p><span class="label label-success"><%= t(job.category, :scope => "job.category") %></span></p>
            <hr>
          </div>
        <% end %>
        <p class="text-center"><%= link_to("更多全职工作", jobs_path(:order => "by_fulltime")) %></p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_meetup_groups_for_index.html.erb
<div class="panel panel-default">
  <div class="panel-header">
    <div class="row">
      <span><a href="/groups"><img src="/images/home_tool9.png"></a> </span><span>  活动 </span>
    </div>
  </div>

  <div class="panel-body">
    <div class="row home-meetup">
      <div class="col-md-6">
        <% @online_meetups.each do |meetup_group| %>
          <div class="job-item">
            <p><span class="pull-right">更新于 <%= time_tag(meetup_group.updated_at) %></span></p>
            <h4><%= link_to(meetup_group.title, meetup_group_path(meetup_group)) %></h4>
            <p><i class="fa fa-street-view" aria-hidden="true"></i> <%= meetup_group.city %></p>
            <p><i class="fa fa-clock-o" aria-hidden="true"></i> <%= meetup_group.activity_time %></p>
            <p><span class="label label-success"><%= t(meetup_group.meetup_type, :scope => "meetup_group.meetup_type") %></span></p>
          </div>
          <hr>
        <% end %>
        <p class="text-center"><%= link_to("更多线下活动", meetup_groups_path(:order => "by_offline")) %></p>
      </div>


      <div class="col-md-6">
        <% @offline_meetups.each do |meetup_group| %>
          <div class="job-item">
            <p><span class="pull-right">更新于 <%= time_tag(meetup_group.updated_at) %></span></p>
            <h4><%= link_to(meetup_group.title, meetup_group_path(meetup_group)) %></h4>
            <p><i class="fa fa-street-view" aria-hidden="true"></i> <%= meetup_group.city %></p>
            <p><i class="fa fa-clock-o" aria-hidden="true"></i> <%= meetup_group.activity_time %></p>
            <p><span class="label label-success"><%= t(meetup_group.meetup_type, :scope => "meetup_group.meetup_type") %></span></p>
          </div>
          <hr>
        <% end %>
        <p class="text-center"><%= link_to("更多线上活动", meetup_groups_path(:order => "by_online")) %></p>
      </div>
    </div>

  </div>
</div>

app/views/welcome/_projects_for_index.html.erb
<div class="panel panel-default">
  <div class="panel-header">
    <div class="row">
      <span><a href="/groups"><img src="/images/home_tool1.png"></a> </span><span>  项目评级 </span>
    </div>
  </div>

  <div class="panel-body">
    <% @projects.each do |project| %>
      <div class="col-xl-3 col-lg-2 col-md-2 col-sm-4 col-xs-4">
          <div class="project-card">
              <% if project.logo.present? %>
                <%= link_to image_tag(project.logo.url(:projectlogo)),project_path(project), :target => "_blank" %>
              <% else %>
                <img src="https://inst.eecs.berkeley.edu/~cs194-26/fa14/upload/files/proj3/cs194-fi/images/warm_sky.jpg" alt="Ver post">
              <% end %>
              <div class="card-body secondbase">
                  <h4 class="card-project-grade">
                    <% if project.project_grade.present? %>
                      <span class="label label-danger"><b>项目评分 <%=  project.project_grade.grade %>分</b></span>
                    <% else %>
                      <span class="label label-warning"><b>待评级</b></span>
                    <% end %>
                  </h4>

                  <div class="card-project-title">
                    <h5 class="text-center"><%= link_to(truncate(project.title,:length => 16), project_path(project)) %></h5>
                  </div>
              </div>
          </div>
      </div>
    <% end %>
  </div>
  <hr>
  <p class="text-center"><%= link_to("更多项目", projects_path) %></p>
</div>

app/views/welcome/_search_for_welcome.html.erb
<div class='container home-search'>
  <div class='col-lg-8 col-lg-offset-2'>
    <div class='search-nav home-search-nav'>
        <ul class='nav dropup'>
            <li class='active' data-search-link='/official_articles/search' onclick="showSearch(this); return false;" data-placeholder='搜索你感兴趣的资讯信息...' data-kind='official_articles'>
              <a href='#'>资讯</a>
              <span class='caret'></span>
            </li>
            <li data-search-link='/topics/search' onclick="showSearch(this); return false;" data-placeholder='你的问题是什么...' data-kind='topics'>
                <a href='#'>话题</a>
                <span class='caret'></span>
            </li>
            <li data-search-link='/courses/search' onclick="showSearch(this); return false;" data-placeholder='输入关键词搜索相关课程...' data-kind='courses'>
                <a href='#'>课程</a>
                <span class='caret'></span>
            </li>
            <li data-search-link='/groups/search' onclick="showSearch(this); return false;" data-placeholder='搜索你感兴趣的小组信息...' data-kind='groups'>
                <a href='#'>小组</a>
                <span class='caret'></span>
            </li>
            <li data-search-link='/posts/search' onclick="showSearch(this); return false;" data-placeholder='搜索文章关键词...' data-kind='posts'>
                <a href='#'>文章</a>
                <span class='caret'></span>
            </li>
            <li data-search-link='/projects/search' onclick="showSearch(this); return false;"  data-placeholder='搜索项目的全称或简称...' data-kind='projects'>
                <a href='#'>项目</a>
                <span class='caret'></span>
            </li>
            <li data-search-link='/jobs/search' onclick="showSearch(this); return false;"  data-placeholder='搜索需求方、类别或工作关键词...' data-kind='jobs'>
                <a href='#'>机会</a>
                <span class='caret'></span>
            </li>
            <li data-search-link='/sites/search' onclick="showSearch(this); return false;"  data-placeholder='输入关键词搜索相关网站...' data-kind='sites'>
                <a href='#'>网站</a>
                <span class='caret'></span>
            </li>
        </ul>
    </div>

    <div class="search-input search-preview" >
      <%= form_tag search_official_articles_path , :method => :get, :class => "topics-search-form", :id => "homeSearch" do %>
        <div class="input-group">
          <input  id="homeSearchInput" type="text" class="form-control search-preview-input" name="q" value="<%= params[:q] %>" placeholder="搜索你感兴趣的资讯信息...">

          <span class="input-group-btn">
            <button type="submit" class="btn btn-danger ">
              <span class='ellipsis'>
                  <i class='fa fa-search'></i>
                  搜索
              </span>
            </button>
          </span>
        </div>
      <% end %>
    </div>
  </div>    
</div>

app/views/welcome/_topics_for_index.html.erb
<div class="panel panel-default">
  <div class="panel-header">
    <div class="row">
      <span><a href="/topics"><img src="/images/home_tool5.png"></a> </span><span>  社区 </span>
    </div>
  </div>

  <div class="panel-body">
    <% @topics.each do |topic| %>
      <div class="topic media topic-<%= topic.id %>">
        <div class="avatar media-left">
          <img src= "<%= render_user_avatar(topic.user, 50) %>" style="width:50px; height:50px; border-radius: 50%;">
        </div>
        <div class="infos media-body">
          <div class="title media-heading">

              <%= topic.node.name %> · 
              <%= link_to(topic.title, topic_path(topic)) %>


              <!-- <i class="fa fa-angle-double-up" title="置顶"></i> -->

          </div>
          <div class="info">
            <span class="name">
              <%= topic.user.display_name %>
            </span> • 发布于 <span><%= time_tag(topic.created_at) %></span>
          </div>
        </div>
        <div class="count media-right">
          <% if topic.answers.count > 0 %>
          <span class="badge"><%= topic.answers.count %></span>

          <% end %>
        </div>
      </div>
    <% end %>
    <hr>
    <p class="text-center"><%= link_to("更多话题", topics_path) %></p>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="about-show">
  <img src="https://ww3.sinaimg.cn/large/006tKfTcly1fnwp11y88bj31kw1z8151.jpg">
<div>

app/views/welcome/index.html.erb
<div class="container">
	<%= render "common/flashes" %>
</div>

<div class="">
	<ul class="slideshow">
			<li>
				<!-- <h3>轮播图</h3> -->
				<span>轮播图1</span>
			</li>
			<li>
				<span>轮播图2</span>
			</li>
			<li>
				<span>轮播图3</span>
			</li>
			<li>
				<span>轮播图4</span>
			</li>
	</ul>
</div>

<div class="index-search">
 <%= render "search_for_welcome" %>
</div>

<div class="home-tool">
	<%= render "home_tool" %>
</div>

<br>
<div class="container">
	<div class="row">
		<%= render "articles_for_index" %>
	</div>

	<%= render "topics_for_index" %>
	<%= render "groups_for_index" %>
	<%= render "projects_for_index" %>

	<div class="index-ads">
		<a href="/"><img src="https://ww4.sinaimg.cn/large/006tNc79ly1fnxt2eiv23j31kw098tb0.jpg" alt="广告"></a>
	</div>

	<%= render "meetup_groups_for_index" %>
	<%= render "courses_for_index" %>
	<%= render "jobs_for_index" %>

</div>