config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/about'

  devise_for :users
  resources :users

  resources :official_articles do
    resources :article_comments
    member do
      post :like
      post :unlike
    end
    collection do
      get :search
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  resource :setting do
    member do
      get :password
    end
  end
  
  resources :posts do
    collection do
      get :search
    end
  end  


  get 'topics/node:id', to: 'topics#node', as: 'node_topics'

  resources :topics do
    member do
      post :answer
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      get :ban
      post :action
      
      post :like
      post :unlike
    end
    collection do
      get :search
      get :no_answer
      get :popular

      get :favorites
      # post :preview
    end
    resources :answers do
      member do
        get :answer_to
      end
    end
  end
  resources :post_comments
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      resources :post_comments
      member do
        post :favorite
        post :unfavorite
      end
    end
    collection do
      get :search
    end
  end
  resources :meetup_groups do
    resources :meetup_comments
    collection do
      get :search
      get :about
    end
    
    member do
      post :favorite
      post :unfavorite
    end
        
  end
  resources :jobs do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :site_nodes

  resources :sites do
    collection do
      get :search
    end
  end
  resources :courses do
    resources :course_comments
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :projects do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end

  namespace :account do
    resources :users
    resources :courses
    resources :groups
    resources :posts
    resources :topics
    resources :jobs
    resources :meetup_groups
    resources :passwords
  end

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :groups do
      collection do
        post :bulk_update
      end
      resources :posts
    end
    resources :versions do
      post :undo
    end
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
      collection do
        post :bulk_update
      end
    end
    resources :nodes
    resources :sections
    resources :meetup_groups do
      collection do
        post :bulk_update
      end
    end
    resources :projects do
      collection do
        post :bulk_update
      end
      resource :project_grade, :controller => "project_grades"
    end
    resources :article_categories do
      collection do
        post :bulk_update
      end
    end
    resources :official_articles do
      collection do
        post :bulk_update
      end
    end
    resources :jobs do
      collection do
        post :bulk_update
      end
      member do
        post :publish
        post :hide
      end
    end
    resources :site_nodes do
      collection do
        post :bulk_update
      end
    end
    resources :sites do
      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, :controller => "user_profiles"
      collection do
        post :bulk_update
      end
    end
    resources :courses do
      collection do
        post :bulk_update
      end
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  has_paper_trail
  validates :title, presence: true
  validates :publisher, presence: true

  belongs_to :user

  has_many :job_relationships
  has_many :favors, through: :job_relationships, source: :user  

  CATEGORYS = ["fulltime", "internship"]

  # Scope #
  scope :recent, -> { order("created_at DESC")}
  scope :deadline, -> { order("deadline DESC")}
  scope :published, -> { where(:is_hidden => false)}
  scope :internship_job, -> { where(:category => "internship")}
  scope :fulltime_job, -> { where(:category => "fulltime")}
  scope :random5, -> { limit(5).order("RANDOM()") }

end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = current_user.jobs.recent.paginate(:page => params[:page], :per_page => 10)
    @favorite_jobs = current_user.favorite_jobs.recent.paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_action :require_editor!

  def index

    @jobs = Job.all.recent.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to admin_jobs_path, notice:"更新成功！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path, alert: "删除成功！"
  end

  def bulk_update
    total = 0
    Array(params[:ids]).each do |job_id|
      job = Job.find(job_id)
      job.destroy
      total += 1
    end

    flash[:alert] = "成功完成 #{total} 笔"
    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.is_hidden = false
    @job.save
    redirect_to admin_jobs_path
  end

  def hide
    @job = Job.find(params[:id])
    @job.is_hidden = true
    @job.save
    redirect_to admin_jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :is_hidden, :category, :city, :publisher, :benefit, :introduce, :demand, :deadline, :process, :user_id)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :favorite, :unfavorite]
  before_action :validate_search_key, only: [:search]

  def index
    @jobs = case params[:order]
            when 'by_deadline'
              Job.published.deadline.paginate(:page => params[:page], :per_page => 10)
            when 'by_internship'
              Job.published.recent.internship_job.paginate(:page => params[:page], :per_page => 10)
            when 'by_fulltime'
              Job.published.recent.fulltime_job.paginate(:page => params[:page], :per_page => 10)
            else
              Job.published.recent.paginate(:page => params[:page], :per_page => 10)
            end
  end

  def show
    @job = Job.find(params[:id])
    set_page_title @job.title
    set_page_description "#{@job.introduce}"    
    # 随机推荐5个相同类型的职位（去除当前职位） #
    @commends = Job.published.where.not(:id => @job.id ).random5

    if @job.is_hidden
      flash[:warning] = "该项目已归档！"
      redirect_to jobs_path
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to jobs_path, notice:"更新成功！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path, alert: "删除成功！"
  end

  def search
    if @query_string.present?
      search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.paginate(:page => params[:page], :per_page => 10 )
    end
  end

  # --收藏功能---
  def favorite
    @job = Job.find(params[:id])

    if !current_user.is_favor_of_job?(@job)
      current_user.favorite_job!(@job)
    end
      redirect_to job_path(@job)
  end

  def unfavorite
    @job = Job.find(params[:id])

    if current_user.is_favor_of_job?(@job)
      current_user.unfavorite_job!(@job)
    end
      redirect_to job_path(@job)
  end
  
  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end


  def search_criteria(query_string)
    { :title_cont => query_string }
  end
  
  private

  def job_params
    params.require(:job).permit(:title, :is_hidden, :category, :city, :publisher, :benefit, :introduce, :demand, :deadline, :process, :user_id)
  end
  
end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end  

end

app/views/admin/jobs/_form.html.erb
<%= form_for [:admin,@job] do |f| %>
  <div class="form-group">
    <%= f.label "标题" %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "发布方" %>
    <%= f.text_field :publisher, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "工作类型" %>
    <%= f.select :category, Job::CATEGORYS.map{ |x| [t(x, :scope => "job.category"), x] }, { :include_blank => true }, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "工作城市" %>
    <%= f.text_field :city, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "截止日期" %>
    <%= f.text_field :deadline, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "工作福利" %>
    <%= f.cktext_area :benefit, ckeditor: { language: 'zh-CN'} %>
  </div>

  <div class="form-group">
    <%= f.label "公司介绍" %>
    <%= f.cktext_area :introduce, ckeditor: { language: 'zh-CN'} %>
  </div>

  <div class="form-group">
    <%= f.label "工作要求" %>
    <%= f.cktext_area :demand, ckeditor: { language: 'zh-CN'} %>
  </div>

  <div class="form-group">
    <%= f.label "申请方式" %>
    <%= f.cktext_area :process, ckeditor: { language: 'zh-CN'} %>
  </div>

  <div class="form-group">
    <%= f.submit "提交", :class => "btn btn-primary" %>
  </div>
<% end %>

<script>
  $("#job_deadline").datepicker({ format: "yyyy-mm-dd", language: "<%= I18n.locale %>" });
</script>

app/views/admin/jobs/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">发布招聘公告</div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/jobs/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">招聘管理</h3>
  </div>
  <div class="panel-body">
    <div class="group">
      <%= link_to("新增招聘信息", new_admin_job_path, class: "btn btn-primary pull-right") %>
    </div>

    <p>操作说明：mark</p>
    <hr>

    <!-- Table -->
    <div id="admin_jobs">
      <%= form_tag bulk_update_admin_jobs_path, :class => "form-inline" do %>

        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= check_box_tag "全选", "1", false, :id => "toggle_all" %></th>
              <td>ID</td>
              <td>招聘信息</td>
              <td>工作地点</td>
              <td>发布方</td>
              <td>截止时间</td>
              <td>更新时间</td>
              <td class="opts">操作</td>
            </tr>
          </thead>
          <tbody>
            <% @jobs.each do |job| %>
              <tr>
                <td>
                  <%= check_box_tag "ids[]", job.id %>
                </td>
                <td><%= job.id %></td>
                <td>
                  <%= render_job_status(job) %>
                  <%= link_to(job.title, admin_job_path(job)) %>
                </td>
                <td><%= job.city %></td>
                <td><%= job.publisher %></td>
                <td><%= job.deadline %></td>
                <td><%= time_tag(job.updated_at) %></td>
                <td>
                  <%= link_to "", edit_admin_job_path(job), class: "fa fa-pencil" %>
                  <%= link_to "", admin_job_path(job), 'data-confirm' => '确定删除?', method: :delete, class: "fa fa-trash" %>

                  <% if job.is_hidden %>

                    <%= link_to("Publish", publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success") %>
                  <% else %>
                    <%= link_to("Hide", hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning") %>
                  <% end %>


                </td>
              </tr>
            <% end %>
          </tbody>
        </table><!-- /Table -->
        <p><%= submit_tag "批次删除", :class => "btn btn-danger", :data => { :confirm => "Are you sure?" } %></p>
      <% end %>
      <div class="text-center">
        <%= will_paginate @jobs, renderer: BootstrapPagination::Rails, :previous_label => t('上一页'), :next_label => t('下一页') %>
      </div>
    </div><!-- /admin_jobs -->
  </div><!-- /panel-body -->
</div>

<script>
  // 这个 javascript 会绑事件在 #toggle_all 核选方块上，来做全选效果
  $("#toggle_all").click(function(){
    if ( $(this).prop("checked") ) {
      $("input[name='ids[]']").prop("checked", true);
    } else {
      $("input[name='ids[]']").prop("checked", false);
    }
  })
</script>

app/views/admin/jobs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">发布招聘公告</div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/jobs/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("更新公告", edit_admin_job_path(@job), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @job.title %></h2>
  工作地点：<%= @job.city %>
  <hr>
  最后更新时间：<%= time_tag(job.updated_at) %>
  <hr>
  <h3>发布方</h3>
  <strong><%= @job.publisher %></strong>
  <hr>
  <h3>Benefits</h3>
  <%= sanitize @job.try(:benefit) %>
  <hr>
  <h3>职位介绍</h3>
  <%= sanitize @job.introduce %>
  <hr>
  <h3>申请要求</h3>
  <%= sanitize @job.demand %>
  <hr>
  <h3>截止日期</h3>
  <%= @job.deadline %>
  <hr>
  <h3>申请流程</h3>
  <%= sanitize @job.process %>
</div>