config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/about'

  devise_for :users
  resources :users

  resources :official_articles do
    resources :article_comments
    member do
      post :like
      post :unlike
    end
    collection do
      get :search
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  resource :setting do
    member do
      get :password
    end
  end
  
  resources :posts do
    collection do
      get :search
    end
  end  


  get 'topics/node:id', to: 'topics#node', as: 'node_topics'

  resources :topics do
    member do
      post :answer
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      get :ban
      post :action
      
      post :like
      post :unlike
    end
    collection do
      get :search
      get :no_answer
      get :popular

      get :favorites
      # post :preview
    end
    resources :answers do
      member do
        get :answer_to
      end
    end
  end
  resources :post_comments
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      resources :post_comments
      member do
        post :favorite
        post :unfavorite
      end
    end
    collection do
      get :search
    end
  end
  resources :meetup_groups do
    resources :meetup_comments
    collection do
      get :search
      get :about
    end
    
    member do
      post :favorite
      post :unfavorite
    end
        
  end
  resources :jobs do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :site_nodes

  resources :sites do
    collection do
      get :search
    end
  end
  resources :courses do
    resources :course_comments
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end
  resources :projects do
    collection do
      get :search
    end
    member do
      post :favorite
      post :unfavorite
    end    
  end

  namespace :account do
    resources :users
    resources :courses
    resources :groups
    resources :posts
    resources :topics
    resources :jobs
    resources :meetup_groups
    resources :passwords
  end

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :groups do
      collection do
        post :bulk_update
      end
      resources :posts
    end
    resources :versions do
      post :undo
    end
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
      collection do
        post :bulk_update
      end
    end
    resources :nodes
    resources :sections
    resources :meetup_groups do
      collection do
        post :bulk_update
      end
    end
    resources :projects do
      collection do
        post :bulk_update
      end
      resource :project_grade, :controller => "project_grades"
    end
    resources :article_categories do
      collection do
        post :bulk_update
      end
    end
    resources :official_articles do
      collection do
        post :bulk_update
      end
    end
    resources :jobs do
      collection do
        post :bulk_update
      end
      member do
        post :publish
        post :hide
      end
    end
    resources :site_nodes do
      collection do
        post :bulk_update
      end
    end
    resources :sites do
      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, :controller => "user_profiles"
      collection do
        post :bulk_update
      end
    end
    resources :courses do
      collection do
        post :bulk_update
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_paper_trail
  validates :title, presence: true
  validates :website, presence: true
  validates :whitepaper, presence: true

  belongs_to :user
  has_one :project_grade
  accepts_nested_attributes_for :project_grade

  has_many :project_relationships
  has_many :favors, through: :project_relationships, source: :user  
  
  mount_uploader :logo, ProjectLogoUploader
  
  STATUS = ["draft", "public", "private"]
  validates_inclusion_of :status, :in => STATUS

  # Scope #
  scope :published, -> { where(:status => "public")}
  scope :recent, -> { order("created_at DESC")}
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  before_action :require_editor!

  def index
    @projects = Project.all.recent.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
    # 跟刚才情况一样，如果没有 @project.project_grade，要先新建一个
    # unless @project.project_grade 等同于 if !@project.project_grade 或 if @project.project_grade.nil?
    @project.create_project_grade unless @project.project_grade
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to admin_projects_path
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to admin_projects_path, notice:"更新成功！"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path, alert: "删除成功！"
  end

  def bulk_update
    total = 0
    Array(params[:ids]).each do |project_id|
      project = Project.find(project_id)
      project.destroy
      total += 1
    end

    flash[:alert] = "成功完成 #{total} 笔"
    redirect_to admin_projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :status, :logo, :remove_logo, :ico_start, :ico_end, :ico_url, :website, :slack, :facebook, :telegram,
      :twitter, :weibo, :github, :ico_amount, :whitepaper, :token_amount, :raised_ceiling, :accept_token,
        :token_type, :introduce, :user_id, :project_grade_attributes => [:id, :rating_report, :grade, :project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :unfavorite, :favorite]
  before_action :validate_search_key, only: [:search]

  def index
    @projects = Project.published.recent.paginate(:page => params[:page], :per_page => 28)
  end

  def show
    @project = Project.find(params[:id])
    set_page_title @project.title
    set_page_description "#{@project.introduce}"     
  end

  def edit
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end


  # --收藏功能---
  def favorite
    @project = Project.find(params[:id])

    if !current_user.is_favor_of_project?(@project)
      current_user.favorite_project!(@project)
    end
      redirect_to project_path(@project)
  end

  def unfavorite
    @project = Project.find(params[:id])

    if current_user.is_favor_of_project?(@project)
      current_user.unfavorite_project!(@project)
    end
      redirect_to project_path(@project)
  end
  
   def search
     if @query_string.present?
       search_result = Project.ransack(@search_criteria).result(:distinct => true)
       @projects = search_result.paginate(:page => params[:page], :per_page => 15 )
     end
   end


   protected

   # 取到params[:q]的内容并去掉非法的内容
   def validate_search_key
     @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
     @search_criteria = search_criteria(@query_string)
   end


   def search_criteria(query_string)
     { :title_cont => query_string }
   end

  private

  def project_params
    params.require(:project).permit(:title, :status, :logo, :remove_logo, :ico_start, :ico_end, :ico_url, :website, :slack, :facebook, :telegram,
      :twitter, :weibo, :github, :ico_amount, :whitepaper, :token_amount, :raised_ceiling, :grade, :accept_token,
        :token_type,  :introduce,  :rating_report,  :user_id)
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin,@project] do |f| %>

  <div class="form-group">
    <%= f.label "项目logo" %>
    <%= f.file_field :logo, :class => "form-control" %>
    <% if f.object.logo.present? %>
      <label>
        <%= f.check_box :remove_logo %> 删除logo
      </label>
      <%= link_to f.object.logo.filename, f.object.logo.url, :target => "_blank" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label "项目名称" %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "当前状态" %>
    <%= f.select :status, Project::STATUS.map{ |s| [t(s, :scope => "project.status"), s] }, {}, :class => "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "ico开始时间" %>
    <%= f.text_field :ico_start, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "ico截止时间" %>
    <%= f.text_field :ico_end, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "众筹网站" %>
    <%= f.text_field :ico_url, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "官网" %>
    <%= f.text_field :website, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Slack" %>
    <%= f.text_field :slack, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Facebook" %>
    <%= f.text_field :facebook, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Telegram" %>
    <%= f.text_field :telegram, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Twitter" %>
    <%= f.text_field :twitter, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "微博" %>
    <%= f.text_field :weibo, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Github" %>
    <%= f.text_field :github, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "白皮书" %>
    <%= f.text_field :whitepaper, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "ico代币数量" %>
    <%= f.text_field :ico_amount, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "代币总量" %>
    <%= f.text_field :token_amount, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "硬顶" %>
    <%= f.text_field :raised_ceiling, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "接受币种" %>
    <%= f.text_field :accept_token, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "代币类型" %>
    <%= f.text_field :token_type, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "项目介绍" %>
    <%= f.cktext_area :introduce, ckeditor: { language: 'zh-CN'} %>
  </div>

  <%= f.fields_for :project_grade do |ff| %>
    <div class="form-group">
      <%= ff.label "测评得分" %>
      <%= ff.text_field :grade, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= ff.label "测评报告" %>
      <%= ff.cktext_area :rating_report, ckeditor: { language: 'zh-CN'} %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "提交", :class => "btn btn-primary" %>
  </div>
<% end %>

<script>
  $("#project_ico_start").datepicker({ format: "yyyy-mm-dd", language: "<%= I18n.locale %>" });
  $("#project_ico_end").datepicker({ format: "yyyy-mm-dd", language: "<%= I18n.locale %>" });
</script>

app/views/admin/projects/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">更新项目评级</div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/projects/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">项目评级管理</h3>
  </div>
  <div class="panel-body">
    <div class="group">
      <%= link_to("新增项目信息", new_admin_project_path, class: "btn btn-primary pull-right") %>
    </div>

    <p>操作说明：mark</p>
    <hr>

    <!-- Table -->
    <div id="admin_projects">
      <%= form_tag bulk_update_admin_projects_path, :class => "form-inline" do %>

        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= check_box_tag "全选", "1", false, :id => "toggle_all" %></th>
              <td>ID</td>
              <td>项目名称</td>
              <td>ICO开启时间</td>
              <td>ICO截止时间</td>
              <td>官网</td>
              <td>提交人</td>
              <td class="opts">管理操作</td>
            </tr>
          </thead>
          <tbody>
            <% @projects.each do |project| %>
              <tr>
                <td>
                  <%= check_box_tag "ids[]", project.id %>
                </td>
                <td><%= project.id %></td>
                <td><%= t(project.status, :scope => "project.status") %><%= link_to(project.title, admin_project_path(project)) %></td>
                <td><%= project.ico_start %></td>
                <td><%= project.ico_end %></td>
                <td><%= project.website %></td>
                <td><%= project.user.email %></td>
                <td>
                  <%= link_to '', edit_admin_project_path(project), class: "fa fa-pencil" %>
                  <%= link_to '', admin_project_path(project), 'data-confirm' => '确认删除?' , method: :delete, class: "fa fa-trash" %>

                  <%= link_to "评级", edit_admin_project_project_grade_path(project), :class => "btn btn-xs btn-success" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table><!-- /Table -->
        <p><%= submit_tag "批次删除", :class => "btn btn-danger", :data => { :confirm => "Are you sure?" } %></p>
      <% end %>
      <div class="text-center">
        <%= will_paginate @projects, renderer: BootstrapPagination::Rails, :previous_label => t('上一页'), :next_label => t('下一页') %>
      </div>
    </div><!-- /admin_projects -->
  </div><!-- /panel-body -->
</div>

<script>
  // 这个 javascript 会绑事件在 #toggle_all 核选方块上，来做全选效果
  $("#toggle_all").click(function(){
    if ( $(this).prop("checked") ) {
      $("input[name='ids[]']").prop("checked", true);
    } else {
      $("input[name='ids[]']").prop("checked", false);
    }
  })
</script>

app/views/admin/projects/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">新增项目评级</div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/projects/show.html.erb
<div class="row cc-project">
  <div class="col-md-9">
    <div class="show-content">
      <h4>项目概况</h4>
      <hr/>

      <div class="row ico_start">
        <div class="col-md-2">
          <p>众筹开始时间</p>
        </div>

        <div class="col-md-10">
          <%= @project.ico_start %>
        </div>
      </div>

      <div class="row ico_end">
        <div class="col-md-2">
          <p>众筹结束时间</p>
        </div>

        <div class="col-md-10">
          <%= @project.ico_start %>
        </div>
      </div>

      <div class="row project-information">
        <div class="col-md-2">
          <p>项目发行基本信息</p>
        </div>

        <div class="col-md-10">
          <table class="table table-striped table-bordered text-center">
            <tr>
              <th class="text-center">ICO总量</th>
              <th class="text-center">代币总量</th>
            </tr>
            <tr>
              <td><%= @project.ico_amount %></td>
              <td><%= @project.token_amount %></td>
            </tr>
            <tr>
              <th class="text-center">募资上限</th>
              <th class="text-center">接受币种</th>
            </tr>
            <tr>
              <td><%= @project.raised_ceiling %></td>
              <td><%= @project.accept_token %></td>
            </tr>
            <tr>
              <th class="text-center">代币类型</th>
              <th class="text-center">官网</th>
            </tr>
            <tr>
              <td><%= @project.token_type %></td>
              <td><%= @project.website %></td>
            </tr>
          </table>
        </div>
      </div>

      <div class="row project-introduce">
        <div class="col-md-2">
          <p>项目说明</p>
        </div>

        <div class="col-md-10">
            <%= sanitize @project.introduce %>
        </div>
      </div>
    </div>

    <div class="show-content">
      <h4><%= @project.title %>评级报告————评分<%= @project.project_grade.grade %></h4>
      <hr/>
      <div class="row project-grade">
        <%= sanitize @project.project_grade.rating_report %>
      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="side-content project-website ">
      <h4>链接</h4>
      <hr>
      <table class="table table-hover">
        <tr>
          <td><%= link_to(content_tag(:i," 官网", class: 'fa fa-home'), @project.website) %></td>
          <td><%= link_to(content_tag(:i," Slack", class: 'fa fa-slack'), @project.slack) %></td>
        </tr>
        <tr>
          <td><%= link_to(content_tag(:i," Facebook", class: 'fa fa-facebook-official'), @project.facebook) %></td>
          <td><%= link_to(content_tag(:i," Telegram", class: 'fa fa-telegram'), @project.telegram) %></td>
        </tr>
        <tr>
          <td><%= link_to(content_tag(:i," Twitter", class: 'fa fa-twitter'), @project.twitter) %></td>
          <td><%= link_to(content_tag(:i," 微博", class: 'fa fa-weibo'), @project.weibo) %></td>
        </tr>
        <tr>
          <td><%= link_to(content_tag(:i," Github", class: 'fa fa-github'), @project.github) %></td>
          <td><%= link_to(content_tag(:i," 白皮书", class: 'fa fa-book'), @project.whitepaper) %></td>
        </tr>
      </table>
    </div>
    <div class="side-content project-admin">
      <h4>管理操作</h4>
      <hr>
      <%= link_to("更新项目", edit_admin_project_path(@project), class: "btn btn-default")%> &nbsp; &nbsp;
      <%= link_to("项目列表", admin_projects_path, class: "btn btn-default")%>
    </div>
  </div>
</div>